# Generated by Django 4.0 on 2022-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_descriptions_category_typez_product_stat6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default=3, upload_to=''),
            preserve_default=False,
        ),
    ]
